name: dropout_predictor
description: A Flutter application for predicting student dropout risk using machine learning.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  material_design_icons_flutter: ^7.0.7296
  charts_flutter: ^0.12.0
  fl_chart: ^0.60.0
  http: ^1.1.0
  dio: ^5.3.0
  provider: ^6.0.5
  form_validator: ^1.0.0
  file_picker: ^5.3.3
  csv: ^5.0.3
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.0
  mockito: ^5.4.2

flutter:
  uses-material-design: true

  # Assets section (keep only what exists)
  assets:
    - assets/images/ # Only uncomment if this directory exists

  # Fonts section must exist as an empty list if no fonts are used
  fonts: []
